# .github/workflows/python-ci.yml
name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # adjust as needed

    - name: Show repo files (debug)
      run: |
        echo "Working directory: $(pwd)"
        ls -la

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies from requirements.txt
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "requirements.txt not found at repo root!"
          ls -la .github/workflows || true
          echo "Attempting to install from .github/workflows/requirements.txt"
          if [ -f .github/workflows/requirements.txt ]; then
            pip install -r .github/workflows/requirements.txt
          else
            echo "No requirements file found. Installing pytest only."
            pip install pytest
          fi
        fi

    - name: Show installed packages (debug)
      run: pip list

    - name: Run tests
      run: |
        # run pytest; adjust path if tests are in a subdirectory, e.g., tests/
        pytest -q --maxfail=1
      # If tests are located elsewhere use: pytest path/to/tests

    # Optional: upload test results, coverage, etc.
