# .github/workflows/python-ci.yml
name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # allows manual re-run from the Actions UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Show repo files (debug)
      run: |
        echo "Working directory: $(pwd)"
        echo "=== root listing ==="
        ls -la
        echo "=== .github/workflows listing ==="
        ls -la .github/workflows || true

    - name: Show Python info (debug)
      run: |
        python -V
        which python || true
        python -m site

    - name: Upgrade pip (use python -m pip)
      run: python -m pip install --upgrade pip

    - name: Install dependencies (use python -m pip; prefer repo root requirements.txt)
      run: |
        set -e
        if [ -f requirements.txt ]; then
          echo "Installing from repo root requirements.txt"
          python -m pip install -r requirements.txt
        elif [ -f .github/workflows/requirements.txt ]; then
          echo "Installing from .github/workflows/requirements.txt"
          python -m pip install -r .github/workflows/requirements.txt
        else
          echo "No requirements.txt found; installing pytest only"
          python -m pip install pytest
        fi
        # Ensure pytest is installed (explicit check)
        python - <<'PY'
import importlib.util, sys
if importlib.util.find_spec('pytest') is None:
    print("pytest not detected; installing pytest")
    import subprocess, sys
    subprocess.check_call([sys.executable, "-m", "pip", "install", "pytest"])
else:
    print("pytest detected")
PY

    - name: Show installed packages (debug)
      run: |
        python -m pip --version
        python -m pip list

    - name: Show pytest version & path (debug)
      run: |
        python -m pytest --version || true
        which pytest || true

    - name: Run tests if present
      run: |
        echo "Checking for tests/ directory..."
        if [ -d "tests" ] && [ "$(ls -A tests 2>/dev/null)" ]; then
          echo "Tests found. Running pytest..."
          python -m pytest -q --maxfail=1
        else
          echo "No tests found in tests/; skipping pytest."
        fi
